# Generated by Django 3.1.4 on 2020-12-08 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_banner_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'EXAMPLE', 'verbose_name_plural': 'PLURAL'},
        ),
    ]
